### ISSUE TITLE
No tests folder

### ISSUE THREAD

**Issue by keitheis** [thruflo/pyramid_basemodel#4]
Can't really do `nosetests --cover-package=pyramid_base_model --cover-tests --with-doctest --with-coverage pyramid_basemodel` to contribute.

**Comment by tilgovi** [comment]
I think this is not an issue. The tests are in the docstrings, hence `--with-doctest`.

**Comment by tilgovi** [comment]
Install `mock` and `nose` and it works fine for me.

**Comment by thruflo** [comment]
Equally would be welcome to add a tests folder!
